trigger:
- main

pool: anjalipool

stages:

- stage: npminstall
  displayName: npminstall
  jobs:
  - job:  npminstall
    displayName: npminstall Job
    steps:
    - task: PowerShell@2
      displayName: npm install
      inputs:
        targetType: 'inline'
        script: 'npm install'
    

    - task: PowerShell@2
      displayName: npm run build
      inputs:
        targetType: 'inline'
        script: 'npm run build'
  
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Pipeline.Workspace)'
        artifact: 'build'
        publishLocation: 'pipeline'



